(()=>{var e={};e.id=211,e.ids=[211],e.modules={7849:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external")},2934:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external.js")},5403:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external")},4580:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external.js")},4749:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external")},5869:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},9491:e=>{"use strict";e.exports=require("assert")},2361:e=>{"use strict";e.exports=require("events")},7147:e=>{"use strict";e.exports=require("fs")},3685:e=>{"use strict";e.exports=require("http")},5687:e=>{"use strict";e.exports=require("https")},2037:e=>{"use strict";e.exports=require("os")},1017:e=>{"use strict";e.exports=require("path")},2781:e=>{"use strict";e.exports=require("stream")},6224:e=>{"use strict";e.exports=require("tty")},7310:e=>{"use strict";e.exports=require("url")},3837:e=>{"use strict";e.exports=require("util")},9796:e=>{"use strict";e.exports=require("zlib")},3286:(e,t,r)=>{"use strict";r.r(t),r.d(t,{GlobalError:()=>o.a,__next_app__:()=>u,originalPathname:()=>p,pages:()=>m,routeModule:()=>d,tree:()=>l}),r(1437),r(7764),r(5866);var s=r(3191),i=r(8716),n=r(7922),o=r.n(n),a=r(5231),c={};for(let e in a)0>["default","tree","pages","GlobalError","originalPathname","__next_app__","routeModule"].indexOf(e)&&(c[e]=()=>a[e]);r.d(t,c);let l=["",{children:["payment-Confirm",{children:["__PAGE__",{},{page:[()=>Promise.resolve().then(r.bind(r,1437)),"D:\\programming\\E-commerce\\ali-sleem\\e-commerce\\app\\payment-Confirm\\page.jsx"]}]},{metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,7481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}]},{layout:[()=>Promise.resolve().then(r.bind(r,7764)),"D:\\programming\\E-commerce\\ali-sleem\\e-commerce\\app\\layout.js"],"not-found":[()=>Promise.resolve().then(r.t.bind(r,5866,23)),"next/dist/client/components/not-found-error"],metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,7481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}],m=["D:\\programming\\E-commerce\\ali-sleem\\e-commerce\\app\\payment-Confirm\\page.jsx"],p="/payment-Confirm/page",u={require:r,loadChunk:()=>Promise.resolve()},d=new s.AppPageRouteModule({definition:{kind:i.x.APP_PAGE,page:"/payment-Confirm/page",pathname:"/payment-Confirm",bundlePath:"",filename:"",appPaths:[]},userland:{loaderTree:l}})},1184:(e,t,r)=>{Promise.resolve().then(r.t.bind(r,9404,23))},1437:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>u});var s=r(9510),i=r(1159),n=r(1812),o=r.n(n);/**
 * @license lucide-react v0.383.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let a=e=>e.replace(/([a-z0-9])([A-Z])/g,"$1-$2").toLowerCase(),c=(...e)=>e.filter((e,t,r)=>!!e&&r.indexOf(e)===t).join(" ");/**
 * @license lucide-react v0.383.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */var l={xmlns:"http://www.w3.org/2000/svg",width:24,height:24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round",strokeLinejoin:"round"};/**
 * @license lucide-react v0.383.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let m=(0,i.forwardRef)(({color:e="currentColor",size:t=24,strokeWidth:r=2,absoluteStrokeWidth:s,className:n="",children:o,iconNode:a,...m},p)=>(0,i.createElement)("svg",{ref:p,...l,width:t,height:t,stroke:e,strokeWidth:s?24*Number(r)/Number(t):r,className:c("lucide",n),...m},[...a.map(([e,t])=>(0,i.createElement)(e,t)),...Array.isArray(o)?o:[o]])),p=((e,t)=>{let r=(0,i.forwardRef)(({className:r,...s},n)=>(0,i.createElement)(m,{ref:n,iconNode:t,className:c(`lucide-${a(e)}`,r),...s}));return r.displayName=`${e}`,r})("Check",[["path",{d:"M20 6 9 17l-5-5",key:"1gmf2c"}]]),u=function(){return(0,s.jsxs)("div",{className:"flex flex-col items-center justify-center px-5 mt-4",children:[s.jsx(p,{className:"w-36 h-36"}),s.jsx("h2",{className:"text-[24px]",children:"payment succeful !"}),s.jsx("h2",{children:"We sent an Email with your order confirmation along with digital content"}),s.jsx(o(),{href:"/",className:"p-2 my-6 text-white rounded-md bg-blue-900",children:"Go to Home"})]})}},1812:(e,t,r)=>{"use strict";let{createProxy:s}=r(8570);e.exports=s("D:\\programming\\E-commerce\\ali-sleem\\e-commerce\\node_modules\\next\\dist\\client\\link.js")},7481:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>i});var s=r(6621);let i=e=>[{type:"image/x-icon",sizes:"16x16",url:(0,s.fillMetadataSegment)(".",e.params,"favicon.ico")+""}]}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[948,407,621,907],()=>r(3286));module.exports=s})();